apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: invoice-service
  name: invoice-service
  labels:
    app: invoice-service
spec:
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
        name: invoice-service
    spec:
      containers:
        - name: invoice-service
          image: shreya-intelops/demo-procurement-solution/invoice-service
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 4500
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        