apiVersion: v1
kind: Service
metadata:
  namespace: invoice-service
  labels:
    app: invoice-service
  name: invoice-service
spec:
  ports:
  
    - protocol: TCP
      port: 4500
      targetPort: 4500
   
   
  selector:
    app: invoice-service
  type: ClusterIP
